### PR TITLE
Feature/user plant api

### PR DESCRIPTION
**Pull request by Insanityandme**
This pull request comes with a bunch of new API endpoints:

PATCH request: Update plant on a particular user
PATCH request: Update all plants on a particular user (used for watering all plants for example)
DELETE request: Delete plant by user ID
GET request: Get plant based on user ID and plant ID
GET request + search parameter: Get plant based on user ID and nickname as a search parameter

GET request: fun facts based on ID

Test this locally by going into localhost:7002 and trying the API endpoints using Swagger.

### CODE REVIEW

**Comment by Insanityandme** [comment]
> Looks good to me!

Har du lyckats testa?

**Comment by AhmadToron** [comment]
image
This is happening when adding a plant to a user, it is shown in the database but i always get 404 not found instead of 201

**Comment by AhmadToron** [comment]
image
here is the console error too!

**Comment by AhmadToron** [comment]
image
image
nothing happens when updating plants by user id

**Comment by AhmadToron** [comment]
image
works fine!

**Comment by Insanityandme** [comment]
Ahmads problems are now solved! Please re-pull if you review again

**Review by AhmadToron — APPROVED** [review]

**Comment by Insanityandme** [comment]
DONT FORGET TO ADD the new DB in viktig-info channel if you are trying fun facts

**Pull request merged**
